import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

enum ConversationType {
  Personal = 1,
  Group = 2,
}

interface IConversation {
  Id: string;
  Type: ConversationType;
  Name: string;
  Users: {
    FullName: string;
  }[];
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetch(
    "https://misajsc.amis.vn/chat/api/business/v1/conversations/me?TagIds=",
    {
      headers: {
        accept: "application/json, text/plain, */*",
        "accept-language": "en-US,en;q=0.9,vi;q=0.8",
        "access-control-allow-origin": "*",
        devicename: "Web",
        "response-type": "json",
        "sec-ch-ua":
          '"Google Chrome";v="137", "Chromium";v="137", "Not/A)Brand";v="24"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        cookie: process.env.NEXT_CHAT_COOKIE,
      },
      referrer: "https://misajsc.amis.vn/chat/cv/67db92ff474bf706bf58b5ba",
      referrerPolicy: "strict-origin-when-cross-origin",
      body: null,
      method: "GET",
      mode: "cors",
      credentials: "include",
    }
  );
  const conversations = await data.json();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen overflow-hidden bg-gradient-to-br from-purple-50 to-blue-50 p-2 sm:p-4 md:p-8">
          <div className="h-full flex flex-col w-full max-w-7xl mx-auto backdrop-blur-xl bg-white/30 border-4 border-black rounded-3xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
            <header className="border-b-4 border-black p-4 sm:p-6 bg-white/40 backdrop-blur-md">
              <div className="flex justify-between items-center gap-4">
                <h1 className="text-2xl sm:text-3xl md:text-4xl font-black tracking-tight">
                  LOGO
                </h1>

                {/* Mobile menu */}
                <div className="flex md:hidden"></div>

                {/* Desktop buttons */}
                <div className="hidden sm:flex items-center gap-3">
                  <button className="btn bg-black hover:bg-black/80 text-white rounded-xl border-2 border-black font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                    Sign in
                  </button>
                  <button className="btn rounded-xl border-2 border-black font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                    Settings
                  </button>
                </div>
              </div>
            </header>
            <div className="overflow-hidden flex-1 min-h-0 grid md:grid-cols-[280px_1fr] h-[calc(100vh-6rem)] ">
              <div className="overflow-y-auto hidden md:block border-r-4 border-black bg-white/40">
                <nav className="space-y-2 ">
                  {conversations.map((conversation: IConversation) => (
                    <Link
                      key={conversation.Id}
                      href={`/conversations/${conversation.Id}`}
                    >
                      <button className="flex items-center gap-2 text-lg font-bold p-3 bg-black text-white rounded-xl">
                        {conversation.Type === ConversationType.Group
                          ? conversation.Name
                          : conversation.Users[0]?.FullName}
                      </button>
                    </Link>
                  ))}
                </nav>
              </div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
